name: generator
description: Website generator for Jaguar built using jaguar_martini.
version: 2.1.1
homepage: https://github.com/Jaguar-dart/website
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: ">=2.0.0-dev.60.0 <3.0.0"

dependencies:
  jaguar_martini: # ^1.4.1
    path: ../../jaguar_martini
  stencil: ^2.1.1
  date_format: ^1.0.2

dev_dependencies:
  test: ^1.2.0
